version: 16
Resources:
 - TargetService:
     Type: AWS::ECS::Service
     Properties:
       TaskDefinition: "arn:arn:aws:iam::265637824843:role/ecsTaskExecutionRole",
       LoadBalancerInfo:
         ContainerName: "bluegreencontainer"
         ContainerPort: 8080
