version: 16
Resources:
 - TargetService:
     Type: AWS::ECS::Service
     Properties:
       TaskDefinition: "<ImageURI>"
       LoadBalancerInfo:
         ContainerName: "bluegreencontainer"
         ContainerPort: 8080
