version: 16
Resources:
 - TargetService:
     Type: AWS::ECS::Service
     Properties:
       TaskDefinition: "arn:aws:ecs:us-east-1:265637824843:task-definition/bluegreen-taskdef:1"
       LoadBalancerInfo:
         ContainerName: "bluegreencontainer"
         ContainerPort: 8080
